New permissions
YunoHost-Apps/onlyoffice_ynh pull request #51
Opened 2021-01-12 21:59 UTC by ericgaspar

## Solution
- *New permissions*
- *Small linter warnings*

## PR Status
- [ ] Code finished.
- [ ] Tested with Package_check.
- [ ] Fix or enhancement tested.
- [ ] Upgrade from last version tested.
- [ ] Can be reviewed and tested.

## Package_check results
---
*If you have access to [App Continuous Integration for packagers](https://yunohost.org/#/packaging_apps_ci) you can provide a link to the package_check results like below, replacing '-NUM-' in this link by the PR number and USERNAME by your username on the ci-apps-dev. Or you provide a screenshot or a pastebin of the results*

[![Build Status](https://ci-apps-dev.yunohost.org/jenkins/job/onlyoffice_ynh%20PR-NUM-%20(USERNAME)/badge/icon)](https://ci-apps-dev.yunohost.org/jenkins/job/onlyoffice_ynh%20PR-NUM-%20(USERNAME)/)

2021-01-26 09:01 UTC, ericgaspar commented
!testme

2021-03-08 18:45 UTC, ericgaspar commented
!testme

2021-03-15 17:17 UTC, alexAubin requested changes

2021-03-15 17:17 UTC, alexAubin commented on scripts/upgrade
> +db_pwd=$(ynh_app_setting_get --app=$app --key=psqlpwd)
Gotta handle the migration for this setting ... if in the past it was called db_pwd, gotta move it to psqlpwd in the upgrade script

2021-04-11 17:44 UTC, ericgaspar commented
!testme

2021-04-12 07:39 UTC, ericgaspar commented
!testme

2021-05-06 16:26 UTC, merged